name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'  # Caches node_modules for faster builds

      - name: Install dependencies
        run: npm install || echo "⚠️ npm install failed"

      - name: Run tests
        run: npm test || echo "⚠️ Tests failed, check logs"

      - name: Build application
        run: npm run build || echo "⚠️ Build failed, check logs"
